name: Build and Release Binary

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: load-data/go.mod

      - name: Build binary
        run: |
          cd load-data
          go build -o populate_db main.go

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.0 # Update this version as needed
          release_name: Release v1.0.0
          draft: false
          prerelease: false
          generate_release_notes: true

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: load-data/populate_db
          asset_name: populate_db
          asset_content_type: application/octet-stream
